version: '3.4'
services:
  product-service:
    build:
      context: .
      dockerfile: cmd/product-service/Dockerfile
    environment:
      - BIND_ADDRESS=:80
      - NATS_ADDRESS=nats://nats:4222
    ports:
      - "9000:80"
    networks:
      - coffee-service-network
    depends_on:
      - nats
  order-service:
    build:
      context: .
      dockerfile: cmd/order-service/Dockerfile
    environment:
      - BIND_ADDRESS=:80
      - NATS_ADDRESS=nats://nats:4222
    ports:
      - "9001:80"
    networks:
      - coffee-service-network
    depends_on:
      - nats
      - product-service
  nats:
    image: nats
    ports:
      - "4222:4222" # nats default port
      - "8222:8222" # nats monitor port
    command: "--name nats --http_port 8222"
    networks:
      - coffee-service-network

networks:
  coffee-service-network:
    driver: bridge