version: '3.4'
services:
  product-service-integration-test:
    build:
      context: .
      dockerfile: product-service/integration_tests/infrastructure/Dockerfile
    environment:
      - WAIT_FOR=product-service:80
      - PRODUCT_SERVICE_URL=http://product-service:80
      - NATS_ADDRESS=nats://nats:4222
    networks:
      - coffee-service-network
    depends_on:
      - product-service