version: '3.4'
services:
  test:
    build:
      context: ./coffee-service
      dockerfile: integration_tests/infrastructure/Dockerfile
    environment:
      - WAIT_FOR=api:80
      - COFFEE_SERVICE_URL=http://api:80
      - NATS_ADDRESS=nats://nats:4222

    networks:
      - coffee-service-network
    depends_on:
      - api