version: '3.4'
services:
  product-service-integration-test:
    build:
      context: .
      dockerfile: test/product_service_tests/Dockerfile
    environment:
      - WAIT_FOR=product-service:80
      - WAIT_FOR_NATS=nats:8222
      - PRODUCT_SERVICE_URL=http://product-service:80
      - NATS_ADDRESS=nats://nats:4222
    networks:
      - coffee-service-network
    depends_on:
      - product-service
      - nats