name: CI

on:
  push:
    branches: ['*']
    tags: ['v*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download Dependencies
      run: |
        (cd coffee-service && go mod download)

    - name: Unit tests
      run: make test

    - name: Integration tests
      run:   make integration