name: CI

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.x"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Dependencies
        run: make restore

      - name: Unit tests
        run: make unit

      - name: Integration tests
        run: make integration